#!/bin/bash
where="$(dirname "$(readlink -f "$0")")"

lj=luajit

if [[ -f $where/.run ]]; then
  lj="$where/.run luajit"
fi

if [[ "_$1" == "_--help" ]]; then
cat <<END
Usage: lunadoc [path/to/project/folder]
END
exit
elif [[ $# -eq 1 ]]; then
  cd "$1"
fi

exec $lj -lluarocks.loader <<END
status, message = pcall(require, 'lunadoc')
if not status then
  print('ERROR:', (tostring(message):gsub('^[^:]+:[0-9]+: ','')))
  os.exit(1)
end
END
